### ISSUE TITLE
Switch back to simple InSpec service description

### ISSUE THREAD

**Issue by chris-rock** [dev-sec/postgres-baseline#17]
As highlighted in #16, the inspec test (https://github.com/dev-sec/postgres-baseline/blob/master/controls/postgres_spec.rb#L69-L73) for:
```
describe service(postgres.service) do
   it { should be_installed }
   it { should be_running }
   it { should be_enabled }
end
```

 do not work well across all operating systems. We need to investigate if this is caused by docker or by inspec.

**Comment by schurzi** [comment]
This seems to be fixed now. Please re-open if it is still a problem.
