### ISSUE TITLE
Support sha256 on Postgresql 10+

### ISSUE THREAD

**Issue by pmav99** [dev-sec/postgres-baseline#24]
Postgresql 10+ supports scram-sha256 hashing for passwords. The inspect check though only allows md5.
More info here: https://paquier.xyz/postgresql-2/postgres-10-scram-authentication/ 

https://github.com/dev-sec/postgres-baseline/blob/01175b7ece81d65eb5cb7884f4c4985ce0742493/controls/postgres_spec.rb#L259-L271

**Comment by chris-rock** [comment]
@pmav99 Thank you for raising the issue. As discussed in #23 we should collect the improvements for Postgres 10 and add improvements via PRs to support that.
